# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dispatcher' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dispatcher
  pod 'SwiftySound'
  #pod 'FeedbackEffect'
  pod 'SwiftLocation', '~> 4.0'
  pod "GCDWebServer", "~> 3.0"

end
